import time
import os
import PLCPi
MyPLC = PLCPi.PLCPi('192.168.1.11',502)
MyPLC.Output('R0',0)
MyPLC.Output('R1',0)
MyPLC.Output('R2',0)
MyPLC.Output('R3',0)
while 1:
    MyPLC.Output('R0',0x01)
    time.sleep(.2)
    MyPLC.Output('R0',0x0)
    time.sleep(.2)
    '''
    MyPLC.Output('R0.0',0xFF)#doc ngo vao bit)
    #MyPLC.Output('R3',0xff)
    time.sleep(.2)
    MyPLC.Output('R0.1',0)#doc ngo vao bit)
    #MyPLC.Output('R3',0)
    time.sleep(.2)
    
    MyPLC.Output('R0.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R0.8',0)
    
    MyPLC.Output('R1.0',0xFF)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.1',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R1.8',0)
    
    MyPLC.Output('R2.0',0xFF)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.1',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R2.8',0)
    
    MyPLC.Output('R3.0',0xFF)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.1',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R3.8',0)
    
    MyPLC.Output('R4.0',0xFF)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.1',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R4.8',0)
    
    MyPLC.Output('R5.0',0xFF)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.1',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.2',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.3',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.4',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.5',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.6',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.7',0)#doc ngo vao bit)
    time.sleep(.2)
    MyPLC.Output('R5.8',0)
    '''
    
